~ You must pass encrypted password everytime you try access data. Later web tokens will be used or better yet google/facebook signing. For now it is what it is.
~ trailing commas are not allowed in client.rest

### signin 
POST http://10.0.0.7:5001/auth/signin
Content-Type: application/json

{
  "username": "asudssasFace",
  "password": "Corsnd"
}
### signup
# if email missing 
POST http://10.0.0.7:5001/auth/signup
Content-Type: application/json

{
  "username": "asudssasFace",
  "password": "Corsnd",
  "email": "saesssds"
}
