
### signin
POST http://localhost:5001/auth/signin
Content-Type: application/json

{
  "username": "YourFace",
  "password": "Cornbread"
}
### signup
POST http://localhost:5001/auth/signup
Content-Type: application/json

{
  "username": "Y1osurFace",
  "password": "Corsnbread",
  "email": "examp1sle@gmail.com"
}
