### create new list
POST http://localhost:5001/list
Content-Type: application/json

{
  "username": "asudssasFace",
  "password": "Corsnd",
  "newList": {
    "title": "NewTitle",
    "todos": [{"_id": "Do something", "todo": "anything"}], 
    "roomId": "9437086d-4ac6-446f-afab-2496b525eaed"
  }
}


### create new room
POST http://localhost:5001/room
Content-Type: application/json

{
  "username": "asudssasFace",
  "password": "Corsnd",
  "room": {
    "title": "Titl1232e12"
  }
}